### PR TITLE
Clang tidy - apply 

### PR DESCRIPTION
**Pull request by sven-oly**
Applied 

```
clang-tidy --checks='modernize*, readability*, clang-analyzer-apiModeling'  *.cpp --fix-errors
```

Note that this does not yet apply clang-tidy in the continuous integration. This might be done with this GitHub action: https://github.com/HorstBaerbel/action-clang-tidy

References:
https://www.kdab.com/clang-tidy-part-1-modernize-source-code-using-c11c14/

https://www.electronjs.org/docs/latest/development/clang-tidy
https://www.wholetomato.com/blog/2021/01/08/a-brief-introduction-to-clang-tidy-and-its-role-in-visual-assist/

### CODE REVIEW

**Comment by sven-oly** [comment]
This address #234

**Comment by sven-oly** [comment]
Please take a look at these updates for CPP code.

**Comment by echeran** [comment]
Here's another clang-tidy CI action that builds upon the previously suggested one with inline comments in the review:
https://github.com/marketplace/actions/clang-tidy-review

**Comment by echeran** [comment]
After creating the `compile_commands.txt` file, then I can point to the directory that contains it in the `clang-tidy` command as so, using the `-p` flag:

```
clang-tidy  *.cpp --fix-errors --header-filter='.*' -p .
```

(this example presupposes that the command is being issued from the same directory as `compile_commands.txt`)

**Review by echeran — APPROVED** [review]
LGTM

**Comment by echeran** [comment]
The command to run clang-tidy locally, as mentioned in the comments in the CI workflow file, is:
```
clang-tidy  *.cpp --fix-errors --config-file="clang-tidy-config.yml" -p .
```

**Pull request merged**
