### PR TITLE
Updating schema testing and other small fixes

### PR DESCRIPTION
**Pull request by sven-oly**

### CODE REVIEW

**Comment by sffc** [comment]
This PR contains many commits that are not "data for date time testing" as the PR title suggests; can you fix it?

**Comment by sven-oly** [comment]
So may I merge this?

**Comment by sffc** [comment]
@sven-oly Sorry I missed your update. Can you fix the conflicts and then we merge this?

**Comment by sven-oly** [comment]
Updated for schema verification only, removing unrelated files.

**Comment by sven-oly** [comment]
I'm abandoning this PR and will add the schema in a new branch.

**Pull request closed without merging**
