### PR TITLE
Rust likely_subtags: categorize"minimizeFavorRegion" as "unsupported"

### PR DESCRIPTION
**Pull request by sven-oly**

### CODE REVIEW

**Comment by sven-oly** [comment]
This updates the schema for results, adding error fields in test output.

**Comment by sven-oly** [comment]
This will move about 800 ICU4X failing tests to unsupported for likely subtags, leaving about 200.

**Review by sffc — COMMENTED** [review]
I believe minimizeFavorRegion is unsupported in _all_ current executors so we should mark it as such in the rest of them, too.

**Review by echeran — APPROVED** [review]
LGTM

**Pull request merged**
