### PR TITLE
Fix errors in ICU4J number formatter

### PR DESCRIPTION
**Pull request by echeran**

### CODE REVIEW

**Review by sven-oly — COMMENTED** [review]
This looks good so far!

**Comment by echeran** [comment]
In local testing of 7334 test cases, 7307 pass, 17 fail, 10 errors.

**Review by sven-oly — APPROVED** [review]
Yay!

**Comment by echeran** [comment]
@sffc When you can, take a look to see if the logic for applying the test options is correct according to the ICU4J NumberFormatter APIs. Also, see #171 for some of the issues encountered along the way.

**Pull request merged**
